#include <cstdint>

namespace optkit_intel{
	enum class bdx_unc_m : uint64_t {
		UNC_M_CLOCKTICKS = 0xff, // IMC Uncore clockticks (fixed counter)
		UNC_M_ACT_COUNT = 0x1, // Counts the number of DRAM Activate commands sent on this channel.  Activate commands are issued to open up a page on the DRAM devices so that it can be read or written to with a CAS.  One can calculate the number of Page Misses by subtracting the number of Page Miss precharges from the number of Activates.
		UNC_M_ACT_COUNT_MASK_BYP = 0x800, // DRAM Activate Count -- Activate due to Write
		UNC_M_ACT_COUNT_MASK_RD = 0x100, // DRAM Activate Count -- Activate due to Read
		UNC_M_ACT_COUNT_MASK_WR = 0x200, // DRAM Activate Count -- Activate due to Write
		UNC_M_BYP_CMDS = 0xa1, // TBD
		UNC_M_BYP_CMDS_MASK_ACT = 0x100, // ACT command issued by 2 cycle bypass
		UNC_M_BYP_CMDS_MASK_CAS = 0x200, // CAS command issued by 2 cycle bypass
		UNC_M_BYP_CMDS_MASK_PRE = 0x400, // PRE command issued by 2 cycle bypass
		UNC_M_CAS_COUNT = 0x4, // DRAM RD_CAS and WR_CAS Commands
		UNC_M_CAS_COUNT_MASK_ALL = 0xf00, // DRAM RD_CAS and WR_CAS Commands. All DRAM WR_CAS (w/ and w/out auto-pre)
		UNC_M_CAS_COUNT_MASK_RD = 0x300, // DRAM RD_CAS and WR_CAS Commands. All DRAM Reads (RD_CAS + Underfills)
		UNC_M_CAS_COUNT_MASK_RD_REG = 0x100, // DRAM RD_CAS and WR_CAS Commands. All DRAM RD_CAS (w/ and w/out auto-pre)
		UNC_M_CAS_COUNT_MASK_RD_RMM = 0x2000, // DRAM RD_CAS and WR_CAS Commands. Read CAS issued in RMM
		UNC_M_CAS_COUNT_MASK_RD_UNDERFILL = 0x200, // DRAM RD_CAS and WR_CAS Commands. Underfill Read Issued
		UNC_M_CAS_COUNT_MASK_RD_WMM = 0x1000, // DRAM RD_CAS and WR_CAS Commands. Read CAS issued in WMM
		UNC_M_CAS_COUNT_MASK_WR = 0xc00, // DRAM RD_CAS and WR_CAS Commands. All DRAM WR_CAS (both Modes)
		UNC_M_CAS_COUNT_MASK_WR_RMM = 0x800, // DRAM RD_CAS and WR_CAS Commands. DRAM WR_CAS (w/ and w/out auto-pre) in Read Major Mode
		UNC_M_CAS_COUNT_MASK_WR_WMM = 0x400, // DRAM RD_CAS and WR_CAS Commands. DRAM WR_CAS (w/ and w/out auto-pre) in Write Major Mode
		UNC_M_DCLOCKTICKS = 0x0, // TBD
		UNC_M_DRAM_PRE_ALL = 0x6, // Counts the number of times that the precharge all command was sent.
		UNC_M_DRAM_REFRESH = 0x5, // Counts the number of refreshes issued.
		UNC_M_DRAM_REFRESH_MASK_HIGH = 0x400, // Number of DRAM Refreshes Issued
		UNC_M_DRAM_REFRESH_MASK_PANIC = 0x200, // Number of DRAM Refreshes Issued
		UNC_M_ECC_CORRECTABLE_ERRORS = 0x9, // Counts the number of ECC errors detected and corrected by the iMC on this channel.  This counter is only useful with ECC DRAM devices.  This count will increment one time for each correction regardless of the number of bits corrected.  The iMC can correct up to 4 bit errors in independent channel mode and 8 bit erros in lockstep mode.
		UNC_M_MAJOR_MODES = 0x7, // Counts the total number of cycles spent in a major mode (selected by a filter) on the given channel.  Major modes are channel-wide
		UNC_M_MAJOR_MODES_MASK_ISOCH = 0x800, // Cycles in a Major Mode -- Isoch Major Mode
		UNC_M_MAJOR_MODES_MASK_PARTIAL = 0x400, // Cycles in a Major Mode -- Partial Major Mode
		UNC_M_MAJOR_MODES_MASK_READ = 0x100, // Cycles in a Major Mode -- Read Major Mode
		UNC_M_MAJOR_MODES_MASK_WRITE = 0x200, // Cycles in a Major Mode -- Write Major Mode
		UNC_M_POWER_CHANNEL_DLLOFF = 0x84, // Number of cycles when all the ranks in the channel are in CKE Slow (DLLOFF) mode.
		UNC_M_POWER_CHANNEL_PPD = 0x85, // off is enabled
		UNC_M_POWER_CKE_CYCLES = 0x83, // Number of cycles spent in CKE ON mode.  The filter allows you to select a rank to monitor.  If multiple ranks are in CKE ON mode at one time
		UNC_M_POWER_CKE_CYCLES_MASK_RANK0 = 0x100, // Rank0 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK1 = 0x200, // Rank1 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK2 = 0x400, // Rank2 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK3 = 0x800, // Rank3 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK4 = 0x1000, // Rank4 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK5 = 0x2000, // Rank5 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK6 = 0x4000, // Rank6 -- DIMM ID
		UNC_M_POWER_CKE_CYCLES_MASK_RANK7 = 0x8000, // Rank7 -- DIMM ID
		UNC_M_POWER_CRITICAL_THROTTLE_CYCLES = 0x86, // Counts the number of cycles when the iMC is in critical thermal throttling.  When this happens
		UNC_M_POWER_PCU_THROTTLING = 0x42, // TBD
		UNC_M_POWER_SELF_REFRESH = 0x43, // Counts the number of cycles when the iMC is in self-refresh and the iMC still has a clock.  This happens in some package C-states.  For example
		UNC_M_POWER_THROTTLE_CYCLES = 0x41, // Counts the number of cycles while the iMC is being throttled by either thermal constraints or by the PCU throttling.  It is not possible to distinguish between the two.  This can be filtered by rank.  If multiple ranks are selected and are being throttled at the same time
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK0 = 0x100, // Rank0 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK1 = 0x200, // Rank1 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK2 = 0x400, // Rank2 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK3 = 0x800, // Rank3 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK4 = 0x1000, // Rank4 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK5 = 0x2000, // Rank5 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK6 = 0x4000, // Rank6 -- DIMM ID
		UNC_M_POWER_THROTTLE_CYCLES_MASK_RANK7 = 0x8000, // Rank7 -- DIMM ID
		UNC_M_PREEMPTION = 0x8, // Counts the number of times a read in the iMC preempts another read or write.  Generally reads to an open page are issued ahead of requests to closed pages.  This improves the page hit rate of the system.  However
		UNC_M_PREEMPTION_MASK_RD_PREEMPT_RD = 0x100, // Read Preemption Count -- Read over Read Preemption
		UNC_M_PREEMPTION_MASK_RD_PREEMPT_WR = 0x200, // Read Preemption Count -- Read over Write Preemption
		UNC_M_PRE_COUNT = 0x2, // Counts the number of DRAM Precharge commands sent on this channel.
		UNC_M_PRE_COUNT_MASK_BYP = 0x1000, // DRAM Precharge commands. -- Precharge due to bypass
		UNC_M_PRE_COUNT_MASK_PAGE_CLOSE = 0x200, // DRAM Precharge commands. -- Precharge due to timer expiration
		UNC_M_PRE_COUNT_MASK_PAGE_MISS = 0x100, // DRAM Precharge commands. -- Precharges due to page miss
		UNC_M_PRE_COUNT_MASK_RD = 0x400, // DRAM Precharge commands. -- Precharge due to read
		UNC_M_PRE_COUNT_MASK_WR = 0x800, // DRAM Precharge commands. -- Precharge due to write
		UNC_M_RD_CAS_PRIO = 0xa0, // TBD
		UNC_M_RD_CAS_PRIO_MASK_HIGH = 0x400, // Read CAS issued with HIGH priority
		UNC_M_RD_CAS_PRIO_MASK_LOW = 0x100, // Read CAS issued with LOW priority
		UNC_M_RD_CAS_PRIO_MASK_MED = 0x200, // Read CAS issued with MEDIUM priority
		UNC_M_RD_CAS_PRIO_MASK_PANIC = 0x800, // Read CAS issued with PANIC NON ISOCH priority (starved)
		UNC_M_RD_CAS_RANK0 = 0xb0, // TBD
		UNC_M_RD_CAS_RANK0_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK0_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK0_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK0_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK0_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK0_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK0_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK0_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK0_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK0_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK0_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK0_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK0_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK0_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK0_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK0_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK0_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK0_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK0_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK0_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK0_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RD_CAS_RANK1 = 0xb1, // TBD
		UNC_M_RD_CAS_RANK1_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK1_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK1_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK1_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK1_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK1_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK1_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK1_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK1_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK1_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK1_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK1_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK1_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK1_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK1_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK1_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK1_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK1_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK1_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK1_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK1_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RD_CAS_RANK2 = 0xb2, // TBD
		UNC_M_RD_CAS_RANK2_MASK_BANK0 = 0x0, // RD_CAS Access to Rank 2 -- Bank 0
		UNC_M_RD_CAS_RANK4 = 0xb4, // TBD
		UNC_M_RD_CAS_RANK4_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK4_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK4_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK4_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK4_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK4_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK4_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK4_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK4_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK4_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK4_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK4_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK4_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK4_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK4_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK4_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK4_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK4_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK4_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK4_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK4_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RD_CAS_RANK5 = 0xb5, // TBD
		UNC_M_RD_CAS_RANK5_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK5_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK5_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK5_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK5_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK5_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK5_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK5_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK5_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK5_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK5_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK5_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK5_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK5_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK5_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK5_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK5_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK5_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK5_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK5_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK5_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RD_CAS_RANK6 = 0xb6, // TBD
		UNC_M_RD_CAS_RANK6_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK6_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK6_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK6_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK6_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK6_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK6_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK6_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK6_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK6_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK6_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK6_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK6_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK6_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK6_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK6_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK6_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK6_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK6_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK6_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK6_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RD_CAS_RANK7 = 0xb7, // TBD
		UNC_M_RD_CAS_RANK7_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_RD_CAS_RANK7_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_RD_CAS_RANK7_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_RD_CAS_RANK7_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_RD_CAS_RANK7_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_RD_CAS_RANK7_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_RD_CAS_RANK7_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_RD_CAS_RANK7_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_RD_CAS_RANK7_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_RD_CAS_RANK7_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_RD_CAS_RANK7_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_RD_CAS_RANK7_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_RD_CAS_RANK7_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_RD_CAS_RANK7_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_RD_CAS_RANK7_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_RD_CAS_RANK7_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_RD_CAS_RANK7_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_RD_CAS_RANK7_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_RD_CAS_RANK7_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_RD_CAS_RANK7_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_RD_CAS_RANK7_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_RPQ_CYCLES_NE = 0x11, // Counts the number of cycles that the Read Pending Queue is not empty.  This can then be used to calculate the average occupancy (in conjunction with the Read Pending Queue Occupancy count).  The RPQ is used to schedule reads out to the memory controller and to track the requests.  Requests allocate into the RPQ soon after they enter the memory controller
		UNC_M_RPQ_INSERTS = 0x10, // Counts the number of allocations into the Read Pending Queue.  This queue is used to schedule reads out to the memory controller and to track the requests.  Requests allocate into the RPQ soon after they enter the memory controller
		UNC_M_VMSE_MXB_WR_OCCUPANCY = 0x91, // TBD
		UNC_M_VMSE_WR_PUSH = 0x90, // TBD
		UNC_M_VMSE_WR_PUSH_MASK_RMM = 0x200, // VMSE WR PUSH issued -- VMSE write PUSH issued in RMM
		UNC_M_VMSE_WR_PUSH_MASK_WMM = 0x100, // VMSE WR PUSH issued -- VMSE write PUSH issued in WMM
		UNC_M_WMM_TO_RMM = 0xc0, // TBD
		UNC_M_WMM_TO_RMM_MASK_LOW_THRESH = 0x100, // Transition from WMM to RMM because of low threshold -- Transition from WMM to RMM because of starve counter
		UNC_M_WMM_TO_RMM_MASK_STARVE = 0x200, // Transition from WMM to RMM because of low threshold --
		UNC_M_WMM_TO_RMM_MASK_VMSE_RETRY = 0x400, // Transition from WMM to RMM because of low threshold --
		UNC_M_WPQ_CYCLES_FULL = 0x22, // Counts the number of cycles when the Write Pending Queue is full.  When the WPQ is full
		UNC_M_WPQ_CYCLES_NE = 0x21, // Counts the number of cycles that the Write Pending Queue is not empty.  This can then be used to calculate the average queue occupancy (in conjunction with the WPQ Occupancy Accumulation count).  The WPQ is used to schedule write out to the memory controller and to track the writes.  Requests allocate into the WPQ soon after they enter the memory controller
		UNC_M_WPQ_READ_HIT = 0x23, // Counts the number of times a request hits in the WPQ (write-pending queue).  The iMC allows writes and reads to pass up other writes to different addresses.  Before a read or a write is issued
		UNC_M_WPQ_WRITE_HIT = 0x24, // Counts the number of times a request hits in the WPQ (write-pending queue).  The iMC allows writes and reads to pass up other writes to different addresses.  Before a read or a write is issued
		UNC_M_WRONG_MM = 0xc1, // TBD
		UNC_M_WR_CAS_RANK0 = 0xb8, // TBD
		UNC_M_WR_CAS_RANK0_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK0_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK0_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK0_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK0_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK0_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK0_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK0_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK0_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK0_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK0_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK0_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK0_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK0_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK0_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK0_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK0_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK0_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK0_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK0_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK0_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_WR_CAS_RANK1 = 0xb9, // TBD
		UNC_M_WR_CAS_RANK1_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK1_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK1_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK1_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK1_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK1_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK1_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK1_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK1_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK1_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK1_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK1_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK1_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK1_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK1_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK1_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK1_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK1_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK1_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK1_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK1_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_WR_CAS_RANK4 = 0xbc, // TBD
		UNC_M_WR_CAS_RANK4_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK4_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK4_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK4_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK4_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK4_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK4_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK4_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK4_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK4_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK4_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK4_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK4_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK4_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK4_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK4_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK4_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK4_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK4_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK4_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK4_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_WR_CAS_RANK5 = 0xbd, // TBD
		UNC_M_WR_CAS_RANK5_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK5_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK5_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK5_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK5_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK5_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK5_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK5_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK5_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK5_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK5_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK5_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK5_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK5_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK5_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK5_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK5_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK5_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK5_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK5_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK5_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_WR_CAS_RANK6 = 0xbe, // TBD
		UNC_M_WR_CAS_RANK6_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK6_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK6_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK6_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK6_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK6_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK6_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK6_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK6_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK6_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK6_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK6_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK6_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK6_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK6_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK6_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK6_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK6_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK6_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK6_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK6_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		UNC_M_WR_CAS_RANK7 = 0xbf, // TBD
		UNC_M_WR_CAS_RANK7_MASK_ALLBANKS = 0x1000, // Access to Rank 0 -- All Banks
		UNC_M_WR_CAS_RANK7_MASK_BANK0 = 0x0, // Access to Rank 0 -- Bank 0
		UNC_M_WR_CAS_RANK7_MASK_BANK1 = 0x100, // Access to Rank 0 -- Bank 1
		UNC_M_WR_CAS_RANK7_MASK_BANK10 = 0xa00, // Access to Rank 0 -- Bank 10
		UNC_M_WR_CAS_RANK7_MASK_BANK11 = 0xb00, // Access to Rank 0 -- Bank 11
		UNC_M_WR_CAS_RANK7_MASK_BANK12 = 0xc00, // Access to Rank 0 -- Bank 12
		UNC_M_WR_CAS_RANK7_MASK_BANK13 = 0xd00, // Access to Rank 0 -- Bank 13
		UNC_M_WR_CAS_RANK7_MASK_BANK14 = 0xe00, // Access to Rank 0 -- Bank 14
		UNC_M_WR_CAS_RANK7_MASK_BANK15 = 0xf00, // Access to Rank 0 -- Bank 15
		UNC_M_WR_CAS_RANK7_MASK_BANK2 = 0x200, // Access to Rank 0 -- Bank 2
		UNC_M_WR_CAS_RANK7_MASK_BANK3 = 0x300, // Access to Rank 0 -- Bank 3
		UNC_M_WR_CAS_RANK7_MASK_BANK4 = 0x400, // Access to Rank 0 -- Bank 4
		UNC_M_WR_CAS_RANK7_MASK_BANK5 = 0x500, // Access to Rank 0 -- Bank 5
		UNC_M_WR_CAS_RANK7_MASK_BANK6 = 0x600, // Access to Rank 0 -- Bank 6
		UNC_M_WR_CAS_RANK7_MASK_BANK7 = 0x700, // Access to Rank 0 -- Bank 7
		UNC_M_WR_CAS_RANK7_MASK_BANK8 = 0x800, // Access to Rank 0 -- Bank 8
		UNC_M_WR_CAS_RANK7_MASK_BANK9 = 0x900, // Access to Rank 0 -- Bank 9
		UNC_M_WR_CAS_RANK7_MASK_BANKG0 = 0x1100, // Access to Rank 0 -- Bank Group 0 (Banks 0-3)
		UNC_M_WR_CAS_RANK7_MASK_BANKG1 = 0x1200, // Access to Rank 0 -- Bank Group 1 (Banks 4-7)
		UNC_M_WR_CAS_RANK7_MASK_BANKG2 = 0x1300, // Access to Rank 0 -- Bank Group 2 (Banks 8-11)
		UNC_M_WR_CAS_RANK7_MASK_BANKG3 = 0x1400, // Access to Rank 0 -- Bank Group 3 (Banks 12-15)
		};};