#include <cstdint>
#include <intel_priv.hh>
namespace optkit::intel{
	enum class skx_unc_iio : uint64_t {
		UNC_IO_CLOCKTICKS = 0x1, // IIO clockticks
		UNC_IO_COMP_BUF_INSERTS = 0xc2, // TBD
		UNC_IO_COMP_BUF_INSERTS__MASK__SKX_UNC_IO_COMP_BUF_INSERTS__PORT0 = 0x400ULL | 1ULL << 36, // PCIe Completion Buffer Inserts -- Port 0
		UNC_IO_COMP_BUF_INSERTS__MASK__SKX_UNC_IO_COMP_BUF_INSERTS__PORT1 = 0x400ULL | 2ULL << 36, // PCIe Completion Buffer Inserts -- Port 1
		UNC_IO_COMP_BUF_INSERTS__MASK__SKX_UNC_IO_COMP_BUF_INSERTS__PORT2 = 0x400ULL | 4ULL << 36, // PCIe Completion Buffer Inserts -- Port 2
		UNC_IO_COMP_BUF_INSERTS__MASK__SKX_UNC_IO_COMP_BUF_INSERTS__PORT3 = 0x400ULL | 8ULL << 36, // PCIe Completion Buffer Inserts -- Port 3
		UNC_IO_COMP_BUF_INSERTS__MASK__SKX_UNC_IO_COMP_BUF_INSERTS__ANY_PORT = 0x400ULL | 0xfULL << 36, // PCIe Completion Buffer Inserts -- Any port
		UNC_IO_COMP_BUF_OCCUPANCY = 0xd5, // TBD
		UNC_IO_DATA_REQ_BY_CPU = 0xc0, // Number of double word (4 bytes) requests initiated by the main die to the attached device.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART0 = 0x4000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART1 = 0x4000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART2 = 0x4000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART3 = 0x4000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_VTD0 = 0x4000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_VTD1 = 0x4000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART0 = 0x1000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART1 = 0x1000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART2 = 0x1000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART3 = 0x1000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_VTD0 = 0x1000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_VTD1 = 0x1000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART0 = 0x8000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART1 = 0x8000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART2 = 0x8000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART3 = 0x8000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_VTD0 = 0x8000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_VTD1 = 0x8000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART0 = 0x2000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART1 = 0x2000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART2 = 0x2000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART3 = 0x2000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_VTD0 = 0x2000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_VTD1 = 0x2000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART0 = 0x400ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART1 = 0x400ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART2 = 0x400ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART3 = 0x400ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_VTD0 = 0x400ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_VTD1 = 0x400ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_ANY = 0x400ULL | 0x3fULL << 36, // Data requested by the CPU -- Core reading from any source
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART0 = 0x100ULL | 1ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART1 = 0x100ULL | 2ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART2 = 0x100ULL | 4ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART3 = 0x100ULL | 8ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_VTD0 = 0x100ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_VTD1 = 0x100ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_ANY = 0x100ULL | 0x3fULL << 36, // Data requested by the CPU -- Core writing
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART0 = 0x800ULL | 0x1ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART1 = 0x800ULL | 0x2ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART2 = 0x800ULL | 0x4ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART3 = 0x800ULL | 0x8ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_VTD0 = 0x800ULL | 0x10ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_VTD1 = 0x800ULL | 0x20ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_ANY = 0x800ULL | 0x3fULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART0 = 0x200ULL | 0x1ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART1 = 0x200ULL | 0x2ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART2 = 0x200ULL | 0x4ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART3 = 0x200ULL | 0x8ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_VTD0 = 0x200ULL | 0x10ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_VTD1 = 0x200ULL | 0x20ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_ANY = 0x200ULL | 0x3fULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_DATA_REQ_OF_CPU = 0x83, // Number of double word (4 bytes) requests the attached device made of the main die.
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART0 = 0x1000ULL | 0x1ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART1 = 0x1000ULL | 0x2ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART2 = 0x1000ULL | 0x4ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART3 = 0x1000ULL | 0x8ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_VTD0 = 0x1000ULL | 0x10ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_VTD1 = 0x1000ULL | 0x20ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART0 = 0x2000ULL | 0x1ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART1 = 0x2000ULL | 0x2ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART2 = 0x2000ULL | 0x4ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART3 = 0x2000ULL | 0x8ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART0 = 0x400ULL| 0x1ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART1 = 0x400ULL| 0x2ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART2 = 0x400ULL| 0x4ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART3 = 0x400ULL| 0x8ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_VTD0 = 0x400ULL| 0x10ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_VTD1 = 0x400ULL| 0x20ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_ANY = 0x400ULL | 0x3fULL << 36, // Data requested by the CPU -- Core reading from any DRAM source
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART0 = 0x100ULL | 0x1ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART1 = 0x100ULL | 0x2ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART2 = 0x100ULL | 0x4ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART3 = 0x100ULL | 0x8ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_VTD0 = 0x100ULL | 0x10ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_VTD1 = 0x100ULL | 0x20ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART0 = 0x4000ULL | 0x1ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART1 = 0x4000ULL | 0x2ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART2 = 0x4000ULL | 0x4ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART3 = 0x4000ULL | 0x8ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_VTD0 = 0x4000ULL | 0x10ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_VTD1 = 0x4000ULL | 0x20ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART0 = 0x800ULL | 0x1ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART1 = 0x800ULL | 0x2ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART2 = 0x800ULL | 0x4ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART3 = 0x800ULL | 0x8ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_VTD0 = 0x800ULL | 0x10ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_VTD1 = 0x800ULL | 0x20ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART0 = 0x200ULL | 0x1ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART1 = 0x200ULL | 0x2ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART2 = 0x200ULL | 0x4ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART3 = 0x200ULL | 0x8ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_VTD0 = 0x200ULL | 0x10ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_DATA_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_VTD1 = 0x200ULL | 0x20ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_LINK_NUM_CORR_ERR = 0xf, // TBD
		UNC_IO_LINK_NUM_RETRIES = 0xe, // TBD
		UNC_IO_MASK_MATCH = 0x21, // TBD
		UNC_IO_MASK_MATCH_AND = 0x2, // Asserted if all bits specified by mask match
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__BUS0 = 0x100, // AND Mask/match for debug bus -- Non-PCIE bus
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__BUS0_BUS1 = 0x800, // AND Mask/match for debug bus -- Non-PCIE bus and PCIE bus
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__BUS0_NOT_BUS1 = 0x400, // AND Mask/match for debug bus -- Non-PCIE bus and !(PCIE bus)
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__BUS1 = 0x200, // AND Mask/match for debug bus -- PCIE bus
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__NOT_BUS0_BUS1 = 0x1000, // AND Mask/match for debug bus -- !(Non-PCIE bus) and PCIE bus
		UNC_IO_MASK_MATCH_AND__MASK__SKX_UNC_IO_MASK_MATCH_AND__NOT_BUS0_NOT_BUS1 = 0x2000, // AND Mask/match for debug bus --
		UNC_IO_MASK_MATCH_OR = 0x3, // Asserted if any bits specified by mask match
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__BUS0 = 0x100, // OR Mask/match for debug bus -- Non-PCIE bus
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__BUS0_BUS1 = 0x800, // OR Mask/match for debug bus -- Non-PCIE bus and PCIE bus
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__BUS0_NOT_BUS1 = 0x400, // OR Mask/match for debug bus -- Non-PCIE bus and !(PCIE bus)
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__BUS1 = 0x200, // OR Mask/match for debug bus -- PCIE bus
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__NOT_BUS0_BUS1 = 0x1000, // OR Mask/match for debug bus -- !(Non-PCIE bus) and PCIE bus
		UNC_IO_MASK_MATCH_OR__MASK__SKX_UNC_IO_MASK_MATCH_OR__NOT_BUS0_NOT_BUS1 = 0x2000, // OR Mask/match for debug bus -- !(Non-PCIE bus) and !(PCIE bus)
		UNC_IO_NOTHING = 0x0, // TBD
		UNC_IO_SYMBOL_TIMES = 0x82, // Gen1 - increment once every 4nS
		UNC_IO_TXN_REQ_BY_CPU = 0xc1, // Also known as Outbound.  Number of requests
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART0 = 0x4000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART1 = 0x4000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART2 = 0x4000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_PART3 = 0x4000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_VTD0 = 0x4000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_READ_VTD1 = 0x4000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART0 = 0x1000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART1 = 0x1000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART2 = 0x1000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_PART3 = 0x1000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_VTD0 = 0x1000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__CFG_WRITE_VTD1 = 0x1000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards PCICFG spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART0 = 0x8000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART1 = 0x8000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART2 = 0x8000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_PART3 = 0x8000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_VTD0 = 0x8000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_READ_VTD1 = 0x8000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART0 = 0x2000ULL | 0x1ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART1 = 0x2000ULL | 0x2ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART2 = 0x2000ULL | 0x4ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_PART3 = 0x2000ULL | 0x8ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_VTD0 = 0x2000ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__IO_WRITE_VTD1 = 0x2000ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards IO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART0 = 0x400ULL | 0x1ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART1 = 0x400ULL | 0x2ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART2 = 0x400ULL | 0x4ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_PART3 = 0x400ULL | 0x8ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_VTD0 = 0x400ULL | 0x10ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_VTD1 = 0x400ULL | 0x20ULL << 36, // Data requested by the CPU -- Core reading from Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_READ_ANY = 0x400ULL | 0x3fULL << 36, // Data requested by the CPU -- Core reading from any source
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART0 = 0x100ULL | 1ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART1 = 0x100ULL | 2ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART2 = 0x100ULL | 4ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_PART3 = 0x100ULL | 8ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_VTD0 = 0x100ULL | 0x10ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_VTD1 = 0x100ULL | 0x20ULL << 36, // Data requested by the CPU -- Core writing to Cards MMIO spacce
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__MEM_WRITE_ANY = 0x100ULL | 0x3fULL << 36, // Data requested by the CPU -- Core writing
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART0 = 0x800ULL | 0x1ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART1 = 0x800ULL | 0x2ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART2 = 0x800ULL | 0x4ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_PART3 = 0x800ULL | 0x8ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_VTD0 = 0x800ULL | 0x10ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_VTD1 = 0x800ULL | 0x20ULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_READ_ANY = 0x800ULL | 0x3fULL << 36, // Another card (different IIO stack) reading from this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART0 = 0x200ULL | 0x1ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART1 = 0x200ULL | 0x2ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART2 = 0x200ULL | 0x4ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_PART3 = 0x200ULL | 0x8ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_VTD0 = 0x200ULL | 0x10ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_VTD1 = 0x200ULL | 0x20ULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_BY_CPU__MASK__SKX_UNC_IO_DATA_REQ_BY_CPU__PEER_WRITE_ANY = 0x200ULL | 0x3fULL << 36, // Another card (different IIO stack) writing to this card.
		UNC_IO_TXN_REQ_OF_CPU = 0x84, // Also known as Inbound.  Number of 64 byte cache line requests initiated by the attached device.
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART0 = 0x1000ULL | 0x1ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART1 = 0x1000ULL | 0x2ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART2 = 0x1000ULL | 0x4ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_PART3 = 0x1000ULL | 0x8ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_VTD0 = 0x1000ULL | 0x10ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMIC_VTD1 = 0x1000ULL | 0x20ULL << 36, // Data requested of the CPU -- Atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART0 = 0x2000ULL | 0x1ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART1 = 0x2000ULL | 0x2ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART2 = 0x2000ULL | 0x4ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__ATOMICCMP_PART3 = 0x2000ULL | 0x8ULL << 36, // Data requested of the CPU -- Completion of atomic requests targeting DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART0 = 0x400ULL| 0x1ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART1 = 0x400ULL| 0x2ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART2 = 0x400ULL| 0x4ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_PART3 = 0x400ULL| 0x8ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_VTD0 = 0x400ULL| 0x10ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_VTD1 = 0x400ULL| 0x20ULL << 36, // Data requested of the CPU -- Card reading from DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_READ_ANY = 0x400ULL | 0x3fULL << 36, // Data requested by the CPU -- Core reading from any DRAM source
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART0 = 0x100ULL | 0x1ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART1 = 0x100ULL | 0x2ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART2 = 0x100ULL | 0x4ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_PART3 = 0x100ULL | 0x8ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_VTD0 = 0x100ULL | 0x10ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MEM_WRITE_VTD1 = 0x100ULL | 0x20ULL << 36, // Data requested of the CPU -- Card writing to DRAM
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART0 = 0x4000ULL | 0x1ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART1 = 0x4000ULL | 0x2ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART2 = 0x4000ULL | 0x4ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_PART3 = 0x4000ULL | 0x8ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_VTD0 = 0x4000ULL | 0x10ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__MSG_VTD1 = 0x4000ULL | 0x20ULL << 36, // Data requested of the CPU -- Messages
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART0 = 0x800ULL | 0x1ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART1 = 0x800ULL | 0x2ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART2 = 0x800ULL | 0x4ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_PART3 = 0x800ULL | 0x8ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_VTD0 = 0x800ULL | 0x10ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_READ_VTD1 = 0x800ULL | 0x20ULL << 36, // Data requested of the CPU -- Card reading from another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART0 = 0x200ULL | 0x1ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART1 = 0x200ULL | 0x2ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART2 = 0x200ULL | 0x4ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_PART3 = 0x200ULL | 0x8ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_VTD0 = 0x200ULL | 0x10ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_TXN_REQ_OF_CPU__MASK__SKX_UNC_IO_DATA_REQ_OF_CPU__PEER_WRITE_VTD1 = 0x200ULL | 0x20ULL << 36, // Data requested of the CPU -- Card writing to another Card (same or different stack)
		UNC_IO_VTD_ACCESS = 0x41, // TBD
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__CTXT_MISS = 0x200, // VTd Access -- context cache miss
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__L1_MISS = 0x400, // VTd Access -- L1 miss
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__L2_MISS = 0x800, // VTd Access -- L2 miss
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__L3_MISS = 0x1000, // VTd Access -- L3 miss
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__L4_PAGE_HIT = 0x100, // VTd Access -- Vtd hit
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__TLB1_MISS = 0x8000, // VTd Access -- TLB miss
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__TLB_FULL = 0x4000, // VTd Access -- TLB is full
		UNC_IO_VTD_ACCESS__MASK__SKX_UNC_IO_VTD_ACCESS__TLB_MISS = 0x2000, // VTd Access -- TLB miss
		UNC_IO_VTD_OCCUPANCY = 0x40, // TBD
		
	};
};