#ifndef OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__PROFILING__CONFIG_HH
#define OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__PROFILING__CONFIG_HH

/**
 * @brief GANTT INSTRUMENTATION
*/

#define REC_CORE_PROFILE 0
#define REC_PROFILE 0

#endif