#ifndef OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__PROFILING__CONFIG_HH
#define OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__PROFILING__CONFIG_HH

/**
 * @brief GANTT INSTRUMENTATION
*/

#define OPTKIT_CORE_GANTT_PROFILE 0
#define OPTKIT_GANTT_PROFILE 0

#endif