#!/bin/bash

# Check if the correct number of arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <executable>"
    exit 1
fi

CURRENT_PATH=$(pwd)

# Assign the executable parameter
EXECUTABLE="$@"
   
CPU_VENDOR=$(lscpu | grep 'Vendor ID' | awk '{print $3}')
# Set the call stack method based on CPU vendor
if [ "$CPU_VENDOR" == "GenuineIntel" ]; then
    CALL_STACK_METHOD="lbr"
elif [ "$CPU_VENDOR" == "AuthenticAMD" ]; then
    CALL_STACK_METHOD="dwarf"
else
    echo "Unknown CPU vendor. Defaulting to dwarf call stack method."
    CALL_STACK_METHOD="dwarf"
fi 

# Run perf record to monitor the call stack
sudo perf record --call-graph "$CALL_STACK_METHOD" $EXECUTABLE

# Change permissions of perf files for reporting
sudo chmod a+rwx perf*

mv perf* $CURRENT_PATH

# Generate and display the perf report
cd $CURRENT_PATH && sudo perf report



