#!/bin/bash
 
# Extract CPUs for socket 0
socket0_cpus=$(numactl --hardware | awk '/node 0 cpus:/ {print substr($0, index($0, ":") + 2)}')

# Extract CPUs for socket 1
socket1_cpus=$(numactl --hardware | awk '/node 1 cpus:/ {print substr($0, index($0, ":") + 2)}')

print_help() {
    echo "Usage: $0 [OPTION] [<-s socket_number_1 -s socket_number_2> -c command...]"
    
    echo "-------"
    # Print the extracted CPUs for verification
    
    if [[ -n $socket0_cpus ]]; then
	    echo "Socket 0 CPUs: $socket0_cpus"
    fi
    
    if [[ -n $socket1_cpus ]]; then
	    echo "Socket 1 CPUs: $socket1_cpus"
    fi
	 
    echo "-------"

    echo "Options:"
    echo "  --help      Display this help message"
}


if [[ "$1" == "--help" || "$#" == 0 ]]; then
    print_help
    exit 0
fi
 

# Initialize variables
socket0=""
socket1=""
cores=""

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -s)
            shift
            if [[ "$1" == "0" ]]; then
                socket0=1
                cores="$socket0_cpus"
            elif [[ "$1" == "1" ]]; then
                socket1=1
                cores="$socket1_cpus"
            fi
            ;;
        -c)
            shift
            command=$@
            break
            ;;
        *)
            echo "Invalid option: $1"
            print_help
            exit 1
            ;;
    esac
    shift
done

# If no sockets specified, use all CPUs
if [[ -z $socket0 && -z $socket1 ]]; then
    cores="$socket0_cpus $socket1_cpus"
fi

# Flatten the cores variable (remove extra spaces)
cores=$(echo $cores | xargs | tr ' ' ',')

# Execute the command with varying thread counts
max_cores=$(echo $cores | tr ',' ' ' | wc -w)


CORE_FREQ_RANGE="1.1 1.2 1.3 1.4 1.5" # get core frange
UNCORE_FREQ_RANGE="2.0 2.1 2.2 2.3" # get uncore freq range

## frequency loop

for CORE_FREQ in $CORE_FREQ_RANGE
do
    for UNCORE_FREQ in $UNCORE_FREQ_RANGE
    do
        export OPTKIT_UNCORE_FREQ=$UNCORE_FREQ
        export OPTKIT_CORE_FREQ=$CORE_FREQ 
        echo "core freq: $OPTKIT_CORE_FREQ  uncore_freq: $OPTKIT_UNCORE_FREQ"
        #  && taskset -c "$cores" $command
    done
done
