#ifndef OPTIMIZER_TOOLKIT__SRC__PLATFORMS__RENDER__OPENGL__SCENE_OBJECTS_HH
#define OPTIMIZER_TOOLKIT__SRC__PLATFORMS__RENDER__OPENGL__SCENE_OBJECTS_HH

#include <opengl_lights.hh>
#include <opengl_shapes.hh>

#endif