#include <cstdint>

namespace optkit_IBM{
	enum class power4 : uint64_t {
		PM_MRK_LSU_SRQ_INST_VALID = 0x933, // Marked instruction valid in SRQ
		PM_FPU1_SINGLE = 0x127, // FPU1 executed single precision instruction
		PM_DC_PREF_OUT_STREAMS = 0xc36, // Out of prefetch streams
		PM_FPU0_STALL3 = 0x121, // FPU0 stalled in pipe3
		PM_TB_BIT_TRANS = 0x8005, // Time Base bit transition
		PM_GPR_MAP_FULL_CYC = 0x235, // Cycles GPR mapper full
		PM_MRK_ST_CMPL = 0x1003, // Marked store instruction completed
		PM_MRK_LSU_FLUSH_LRQ = 0x3910, // Marked LRQ flushes
		PM_FPU0_STF = 0x122, // FPU0 executed store instruction
		PM_FPU1_FMA = 0x105, // FPU1 executed multiply-add instruction
		PM_L2SA_MOD_TAG = 0xf06, // L2 slice A transition from modified to tagged
		PM_MRK_DATA_FROM_L275_SHR = 0x6c76, // Marked data loaded from L2.75 shared
		PM_1INST_CLB_CYC = 0x450, // Cycles 1 instruction in CLB
		PM_LSU1_FLUSH_ULD = 0xc04, // LSU1 unaligned load flushes
		PM_MRK_INST_FIN = 0x7005, // Marked instruction finished
		PM_MRK_LSU0_FLUSH_UST = 0x911, // LSU0 marked unaligned store flushes
		PM_FPU_FDIV = 0x1100, // FPU executed FDIV instruction
		PM_LSU_LRQ_S0_ALLOC = 0xc26, // LRQ slot 0 allocated
		PM_FPU0_FULL_CYC = 0x203, // Cycles FPU0 issue queue full
		PM_FPU_SINGLE = 0x5120, // FPU executed single precision instruction
		PM_FPU0_FMA = 0x101, // FPU0 executed multiply-add instruction
		PM_MRK_LSU1_FLUSH_ULD = 0x914, // LSU1 marked unaligned load flushes
		PM_LSU1_FLUSH_LRQ = 0xc06, // LSU1 LRQ flushes
		PM_L2SA_ST_HIT = 0xf11, // L2 slice A store hits
		PM_L2SB_SHR_INV = 0xf21, // L2 slice B transition from shared to invalid
		PM_DTLB_MISS = 0x904, // Data TLB misses
		PM_MRK_ST_MISS_L1 = 0x923, // Marked L1 D cache store misses
		PM_EXT_INT = 0x8002, // External interrupts
		PM_MRK_LSU1_FLUSH_LRQ = 0x916, // LSU1 marked LRQ flushes
		PM_MRK_ST_GPS = 0x6003, // Marked store sent to GPS
		PM_GRP_DISP_SUCCESS = 0x5001, // Group dispatch success
		PM_LSU1_LDF = 0x934, // LSU1 executed Floating Point load instruction
		PM_FAB_CMD_ISSUED = 0xf16, // Fabric command issued
		PM_LSU0_SRQ_STFWD = 0xc20, // LSU0 SRQ store forwarded
		PM_CR_MAP_FULL_CYC = 0x204, // Cycles CR logical operation mapper full
		PM_MRK_LSU0_FLUSH_ULD = 0x910, // LSU0 marked unaligned load flushes
		PM_LSU_DERAT_MISS = 0x6900, // DERAT misses
		PM_FPU0_SINGLE = 0x123, // FPU0 executed single precision instruction
		PM_FPU1_FDIV = 0x104, // FPU1 executed FDIV instruction
		PM_FPU1_FEST = 0x116, // FPU1 executed FEST instruction
		PM_FPU0_FRSP_FCONV = 0x111, // FPU0 executed FRSP or FCONV instructions
		PM_MRK_ST_CMPL_INT = 0x3003, // Marked store completed with intervention
		PM_FXU_FIN = 0x3230, // FXU produced a result
		PM_FPU_STF = 0x6120, // FPU executed store instruction
		PM_DSLB_MISS = 0x905, // Data SLB misses
		PM_DATA_FROM_L275_SHR = 0x6c66, // Data loaded from L2.75 shared
		PM_FXLS1_FULL_CYC = 0x214, // Cycles FXU1/LS1 queue full
		PM_L3B0_DIR_MIS = 0xf01, // L3 bank 0 directory misses
		PM_2INST_CLB_CYC = 0x451, // Cycles 2 instructions in CLB
		PM_MRK_STCX_FAIL = 0x925, // Marked STCX failed
		PM_LSU_LMQ_LHR_MERGE = 0x926, // LMQ LHR merges
		PM_FXU0_BUSY_FXU1_IDLE = 0x7002, // FXU0 busy FXU1 idle
		PM_L3B1_DIR_REF = 0xf02, // L3 bank 1 directory references
		PM_MRK_LSU_FLUSH_UST = 0x7910, // Marked unaligned store flushes
		PM_MRK_DATA_FROM_L25_SHR = 0x5c76, // Marked data loaded from L2.5 shared
		PM_LSU_FLUSH_ULD = 0x1c00, // LRQ unaligned load flushes
		PM_MRK_BRU_FIN = 0x2005, // Marked instruction BRU processing finished
		PM_IERAT_XLATE_WR = 0x327, // Translation written to ierat
		PM_LSU0_BUSY = 0xc33, // LSU0 busy
		PM_L2SA_ST_REQ = 0xf10, // L2 slice A store requests
		PM_DATA_FROM_MEM = 0x2c66, // Data loaded from memory
		PM_FPR_MAP_FULL_CYC = 0x201, // Cycles FPR mapper full
		PM_FPU1_FULL_CYC = 0x207, // Cycles FPU1 issue queue full
		PM_FPU0_FIN = 0x113, // FPU0 produced a result
		PM_3INST_CLB_CYC = 0x452, // Cycles 3 instructions in CLB
		PM_DATA_FROM_L35 = 0x3c66, // Data loaded from L3.5
		PM_L2SA_SHR_INV = 0xf05, // L2 slice A transition from shared to invalid
		PM_MRK_LSU_FLUSH_SRQ = 0x4910, // Marked SRQ flushes
		PM_THRESH_TIMEO = 0x2003, // Threshold timeout
		PM_FPU_FSQRT = 0x6100, // FPU executed FSQRT instruction
		PM_MRK_LSU0_FLUSH_LRQ = 0x912, // LSU0 marked LRQ flushes
		PM_FXLS0_FULL_CYC = 0x210, // Cycles FXU0/LS0 queue full
		PM_DATA_TABLEWALK_CYC = 0x936, // Cycles doing data tablewalks
		PM_FPU0_ALL = 0x103, // FPU0 executed add
		PM_FPU0_FEST = 0x112, // FPU0 executed FEST instruction
		PM_DATA_FROM_L25_MOD = 0x8c66, // Data loaded from L2.5 modified
		PM_LSU_LMQ_SRQ_EMPTY_CYC = 0x2002, // Cycles LMQ and SRQ empty
		PM_FPU_FEST = 0x3110, // FPU executed FEST instruction
		PM_0INST_FETCH = 0x8327, // No instructions fetched
		PM_LARX_LSU1 = 0xc77, // Larx executed on LSU1
		PM_LD_MISS_L1_LSU0 = 0xc12, // LSU0 L1 D cache load misses
		PM_L1_PREF = 0xc35, // L1 cache data prefetches
		PM_FPU1_STALL3 = 0x125, // FPU1 stalled in pipe3
		PM_BRQ_FULL_CYC = 0x205, // Cycles branch queue full
		PM_LARX = 0x4c70, // Larx executed
		PM_MRK_DATA_FROM_L35 = 0x3c76, // Marked data loaded from L3.5
		PM_WORK_HELD = 0x2001, // Work held
		PM_MRK_LD_MISS_L1_LSU0 = 0x920, // LSU0 L1 D cache load misses
		PM_FXU_IDLE = 0x5002, // FXU idle
		PM_INST_CMPL = 0x8001, // Instructions completed
		PM_LSU1_FLUSH_UST = 0xc05, // LSU1 unaligned store flushes
		PM_LSU0_FLUSH_ULD = 0xc00, // LSU0 unaligned load flushes
		PM_INST_FROM_L2 = 0x3327, // Instructions fetched from L2
		PM_DATA_FROM_L3 = 0x1c66, // Data loaded from L3
		PM_FPU0_DENORM = 0x120, // FPU0 received denormalized data
		PM_FPU1_FMOV_FEST = 0x114, // FPU1 executing FMOV or FEST instructions
		PM_GRP_DISP_REJECT = 0x8003, // Group dispatch rejected
		PM_INST_FETCH_CYC = 0x323, // Cycles at least 1 instruction fetched
		PM_LSU_LDF = 0x8930, // LSU executed Floating Point load instruction
		PM_INST_DISP = 0x221, // Instructions dispatched
		PM_L2SA_MOD_INV = 0xf07, // L2 slice A transition from modified to invalid
		PM_DATA_FROM_L25_SHR = 0x5c66, // Data loaded from L2.5 shared
		PM_FAB_CMD_RETRIED = 0xf17, // Fabric command retried
		PM_L1_DCACHE_RELOAD_VALID = 0xc64, // L1 reload data source valid
		PM_MRK_GRP_ISSUED = 0x6005, // Marked group issued
		PM_FPU_FULL_CYC = 0x5200, // Cycles FPU issue queue full
		PM_FPU_FMA = 0x2100, // FPU executed multiply-add instruction
		PM_MRK_CRU_FIN = 0x4005, // Marked instruction CRU processing finished
		PM_MRK_LSU1_FLUSH_UST = 0x915, // LSU1 marked unaligned store flushes
		PM_MRK_FXU_FIN = 0x6004, // Marked instruction FXU processing finished
		PM_BR_ISSUED = 0x330, // Branches issued
		PM_EE_OFF = 0x233, // Cycles MSR(EE) bit off
		PM_INST_FROM_L3 = 0x5327, // Instruction fetched from L3
		PM_ITLB_MISS = 0x900, // Instruction TLB misses
		PM_FXLS_FULL_CYC = 0x8210, // Cycles FXLS queue is full
		PM_FXU1_BUSY_FXU0_IDLE = 0x4002, // FXU1 busy FXU0 idle
		PM_GRP_DISP_VALID = 0x223, // Group dispatch valid
		PM_L2SC_ST_HIT = 0xf15, // L2 slice C store hits
		PM_MRK_GRP_DISP = 0x1002, // Marked group dispatched
		PM_L2SB_MOD_TAG = 0xf22, // L2 slice B transition from modified to tagged
		PM_INST_FROM_L25_L275 = 0x2327, // Instruction fetched from L2.5/L2.75
		PM_LSU_FLUSH_UST = 0x2c00, // SRQ unaligned store flushes
		PM_L2SB_ST_HIT = 0xf13, // L2 slice B store hits
		PM_FXU1_FIN = 0x236, // FXU1 produced a result
		PM_L3B1_DIR_MIS = 0xf03, // L3 bank 1 directory misses
		PM_4INST_CLB_CYC = 0x453, // Cycles 4 instructions in CLB
		PM_GRP_CMPL = 0x7003, // Group completed
		PM_DC_PREF_L2_CLONE_L3 = 0xc27, // L2 prefetch cloned with L3
		PM_FPU_FRSP_FCONV = 0x7110, // FPU executed FRSP or FCONV instructions
		PM_5INST_CLB_CYC = 0x454, // Cycles 5 instructions in CLB
		PM_MRK_LSU0_FLUSH_SRQ = 0x913, // LSU0 marked SRQ flushes
		PM_MRK_LSU_FLUSH_ULD = 0x8910, // Marked unaligned load flushes
		PM_8INST_CLB_CYC = 0x457, // Cycles 8 instructions in CLB
		PM_LSU_LMQ_FULL_CYC = 0x927, // Cycles LMQ full
		PM_ST_REF_L1_LSU0 = 0xc11, // LSU0 L1 D cache store references
		PM_LSU0_DERAT_MISS = 0x902, // LSU0 DERAT misses
		PM_LSU_SRQ_SYNC_CYC = 0x932, // SRQ sync duration
		PM_FPU_STALL3 = 0x2120, // FPU stalled in pipe3
		PM_MRK_DATA_FROM_L2 = 0x4c76, // Marked data loaded from L2
		PM_FPU0_FMOV_FEST = 0x110, // FPU0 executed FMOV or FEST instructions
		PM_LSU0_FLUSH_SRQ = 0xc03, // LSU0 SRQ flushes
		PM_LD_REF_L1_LSU0 = 0xc10, // LSU0 L1 D cache load references
		PM_L2SC_SHR_INV = 0xf25, // L2 slice C transition from shared to invalid
		PM_LSU1_FLUSH_SRQ = 0xc07, // LSU1 SRQ flushes
		PM_LSU_LMQ_S0_ALLOC = 0x935, // LMQ slot 0 allocated
		PM_ST_REF_L1 = 0x7c10, // L1 D cache store references
		PM_LSU_SRQ_EMPTY_CYC = 0x4003, // Cycles SRQ empty
		PM_FPU1_STF = 0x126, // FPU1 executed store instruction
		PM_L3B0_DIR_REF = 0xf00, // L3 bank 0 directory references
		PM_RUN_CYC = 0x1005, // Run cycles
		PM_LSU_LMQ_S0_VALID = 0x931, // LMQ slot 0 valid
		PM_LSU_LRQ_S0_VALID = 0xc22, // LRQ slot 0 valid
		PM_LSU0_LDF = 0x930, // LSU0 executed Floating Point load instruction
		PM_MRK_IMR_RELOAD = 0x922, // Marked IMR reloaded
		PM_7INST_CLB_CYC = 0x456, // Cycles 7 instructions in CLB
		PM_MRK_GRP_TIMEO = 0x5005, // Marked group completion timeout
		PM_FPU_FMOV_FEST = 0x8110, // FPU executing FMOV or FEST instructions
		PM_GRP_DISP_BLK_SB_CYC = 0x231, // Cycles group dispatch blocked by scoreboard
		PM_XER_MAP_FULL_CYC = 0x202, // Cycles XER mapper full
		PM_ST_MISS_L1 = 0xc23, // L1 D cache store misses
		PM_STOP_COMPLETION = 0x3001, // Completion stopped
		PM_MRK_GRP_CMPL = 0x4004, // Marked group completed
		PM_ISLB_MISS = 0x901, // Instruction SLB misses
		PM_CYC = 0x7, // Processor cycles
		PM_LD_MISS_L1_LSU1 = 0xc16, // LSU1 L1 D cache load misses
		PM_STCX_FAIL = 0x921, // STCX failed
		PM_LSU1_SRQ_STFWD = 0xc24, // LSU1 SRQ store forwarded
		PM_GRP_DISP = 0x2004, // Group dispatches
		PM_DATA_FROM_L2 = 0x4c66, // Data loaded from L2
		PM_L2_PREF = 0xc34, // L2 cache prefetches
		PM_FPU0_FPSCR = 0x130, // FPU0 executed FPSCR instruction
		PM_FPU1_DENORM = 0x124, // FPU1 received denormalized data
		PM_MRK_DATA_FROM_L25_MOD = 0x8c76, // Marked data loaded from L2.5 modified
		PM_L2SB_ST_REQ = 0xf12, // L2 slice B store requests
		PM_L2SB_MOD_INV = 0xf23, // L2 slice B transition from modified to invalid
		PM_FPU0_FSQRT = 0x102, // FPU0 executed FSQRT instruction
		PM_LD_REF_L1 = 0x8c10, // L1 D cache load references
		PM_MRK_L1_RELOAD_VALID = 0xc74, // Marked L1 reload data source valid
		PM_L2SB_SHR_MOD = 0xf20, // L2 slice B transition from shared to modified
		PM_INST_FROM_L1 = 0x6327, // Instruction fetched from L1
		PM_1PLUS_PPC_CMPL = 0x5003, // One or more PPC instruction completed
		PM_EE_OFF_EXT_INT = 0x237, // Cycles MSR(EE) bit off and external interrupt pending
		PM_L2SC_SHR_MOD = 0xf24, // L2 slice C transition from shared to modified
		PM_LSU_LRQ_FULL_CYC = 0x212, // Cycles LRQ full
		PM_IC_PREF_INSTALL = 0x325, // Instruction prefetched installed in prefetch buffer
		PM_MRK_LSU1_FLUSH_SRQ = 0x917, // LSU1 marked SRQ flushes
		PM_GCT_FULL_CYC = 0x200, // Cycles GCT full
		PM_INST_FROM_MEM = 0x1327, // Instruction fetched from memory
		PM_FXU_BUSY = 0x6002, // FXU busy
		PM_ST_REF_L1_LSU1 = 0xc15, // LSU1 L1 D cache store references
		PM_MRK_LD_MISS_L1 = 0x1920, // Marked L1 D cache load misses
		PM_MRK_LSU1_INST_FIN = 0xc32, // LSU1 finished a marked instruction
		PM_L1_WRITE_CYC = 0x333, // Cycles writing to instruction L1
		PM_BIQ_IDU_FULL_CYC = 0x324, // Cycles BIQ or IDU full
		PM_MRK_LSU0_INST_FIN = 0xc31, // LSU0 finished a marked instruction
		PM_L2SC_ST_REQ = 0xf14, // L2 slice C store requests
		PM_LSU1_BUSY = 0xc37, // LSU1 busy
		PM_FPU_ALL = 0x5100, // FPU executed add
		PM_LSU_SRQ_S0_ALLOC = 0xc25, // SRQ slot 0 allocated
		PM_GRP_MRK = 0x5004, // Group marked in IDU
		PM_FPU1_FIN = 0x117, // FPU1 produced a result
		PM_DC_PREF_STREAM_ALLOC = 0x907, // D cache new prefetch stream allocated
		PM_BR_MPRED_CR = 0x331, // Branch mispredictions due CR bit setting
		PM_BR_MPRED_TA = 0x332, // Branch mispredictions due to target address
		PM_CRQ_FULL_CYC = 0x211, // Cycles CR issue queue full
		PM_INST_FROM_PREF = 0x7327, // Instructions fetched from prefetch
		PM_LD_MISS_L1 = 0x3c10, // L1 D cache load misses
		PM_STCX_PASS = 0xc75, // Stcx passes
		PM_DC_INV_L2 = 0xc17, // L1 D cache entries invalidated from L2
		PM_LSU_SRQ_FULL_CYC = 0x213, // Cycles SRQ full
		PM_LSU0_FLUSH_LRQ = 0xc02, // LSU0 LRQ flushes
		PM_LSU_SRQ_S0_VALID = 0xc21, // SRQ slot 0 valid
		PM_LARX_LSU0 = 0xc73, // Larx executed on LSU0
		PM_GCT_EMPTY_CYC = 0x1004, // Cycles GCT empty
		PM_FPU1_ALL = 0x107, // FPU1 executed add
		PM_FPU1_FSQRT = 0x106, // FPU1 executed FSQRT instruction
		PM_FPU_FIN = 0x4110, // FPU produced a result
		PM_L2SA_SHR_MOD = 0xf04, // L2 slice A transition from shared to modified
		PM_MRK_LD_MISS_L1_LSU1 = 0x924, // LSU1 L1 D cache load misses
		PM_LSU_SRQ_STFWD = 0x1c20, // SRQ store forwarded
		PM_FXU0_FIN = 0x232, // FXU0 produced a result
		PM_MRK_FPU_FIN = 0x7004, // Marked instruction FPU processing finished
		PM_LSU_BUSY = 0x4c30, // LSU busy
		PM_INST_FROM_L35 = 0x4327, // Instructions fetched from L3.5
		PM_FPU1_FRSP_FCONV = 0x115, // FPU1 executed FRSP or FCONV instructions
		PM_SNOOP_TLBIE = 0x903, // Snoop TLBIE
		PM_FPU0_FDIV = 0x100, // FPU0 executed FDIV instruction
		PM_LD_REF_L1_LSU1 = 0xc14, // LSU1 L1 D cache load references
		PM_MRK_DATA_FROM_L275_MOD = 0x7c76, // Marked data loaded from L2.75 modified
		PM_HV_CYC = 0x3004, // Hypervisor Cycles
		PM_6INST_CLB_CYC = 0x455, // Cycles 6 instructions in CLB
		PM_LR_CTR_MAP_FULL_CYC = 0x206, // Cycles LR/CTR mapper full
		PM_L2SC_MOD_INV = 0xf27, // L2 slice C transition from modified to invalid
		PM_FPU_DENORM = 0x1120, // FPU received denormalized data
		PM_DATA_FROM_L275_MOD = 0x7c66, // Data loaded from L2.75 modified
		PM_LSU1_DERAT_MISS = 0x906, // LSU1 DERAT misses
		PM_IC_PREF_REQ = 0x326, // Instruction prefetch requests
		PM_MRK_LSU_FIN = 0x8004, // Marked instruction LSU processing finished
		PM_MRK_DATA_FROM_L3 = 0x1c76, // Marked data loaded from L3
		PM_MRK_DATA_FROM_MEM = 0x2c76, // Marked data loaded from memory
		PM_LSU0_FLUSH_UST = 0xc01, // LSU0 unaligned store flushes
		PM_LSU_FLUSH_LRQ = 0x6c00, // LRQ flushes
		PM_LSU_FLUSH_SRQ = 0x5c00, // SRQ flushes
		
	};
};