#ifndef OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__CONFIG_HH
#define OPTIMIZER_TOOLKIT_CORE__SRC__UTILS__CONFIG_HH

#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT	24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)

#endif
